### PR TITLE
Added a linear-programming library

### PR DESCRIPTION
**Pull request by svetlyak40wt**

### CODE REVIEW

**Comment by vindarel** [comment]
Thanks again, there are quite a few new libraries to add.

Can you add the licence ? (MIT)

**Comment by svetlyak40wt** [comment]
Added.

By the way, why do all lincense urls have numberic references?

Why can't I make a link to the license by adding just `[MIT][MIT]` instead of `[MIT][200]`?

**Comment by vindarel** [comment]
For no good reason I suppose. I always saw them like that. And numbers are a dabbrev-expand away, so it didn't bother me…

**Comment by svetlyak40wt** [comment]
Seems I need to learn how to use "dabbrev-expand".

However, I've edited this page right in the GitHub's web editor. It is enough when you just want to add a line or fix a typo.

**Pull request merged**
