### PR TITLE
adding mcclim

### PR DESCRIPTION
**Pull request by azzamsa**
cool GUI toolkit

### CODE REVIEW

**Comment by vindarel** [comment]
and with a big manual \o/ (if you know of example applications or blog posts, that would be a nice addition too IMO. A quick search didn't return a lot).

**Comment by azzamsa** [comment]
@vindarel what about this ?
https://common-lisp.net/project/mcclim/excite.html

**Comment by vindarel** [comment]
oops :) I didn't get "Get Excited" at first sight and was looking for this in the Resources section. 

Now a youtube video ? :]

**Comment by vindarel** [comment]
Wouldn't Aws-sign4 better fit into "Third party APIs" ?

(Also, this PR isn't isolated for McClim any more).

**Comment by CodyReichert** [comment]
Awesome - thanks! I agree - can we move `aws-sign4` into "Third Party APIs"?

The others look great, so after that let's merge it.

**Comment by azzamsa** [comment]
Done.
Cody, we miss you. you have not been here for while.

Now I am working on [awesome-cl-software](https://github.com/azzamsa/awesome-cl-software)

**Comment by azzamsa** [comment]
thanks :)

**Comment by vindarel** [comment]
@azzamsa hello, please don't forget to add McClim and others :)

**Pull request closed without merging**
