### PR TITLE
Atlas N-libraries

### PR DESCRIPTION
**Pull request by aartaka**
We've built a lot of libraries in Atlas, most of them based on web browsing and graphical application use-cases. These often cover the niches in between other libraries, so it might be useful to add these to `awesome-cl`.

This PR has every library addition in a separate commit, so that these can be cherry-picked and squashed at will.

Thanks!

### CODE REVIEW

**Comment by Hexstream** [comment]
Clickable links for easier review: [NJSON](https://github.com/atlas-engineer/njson), [nclasses](https://github.com/atlas-engineer/nclasses), [ndebug](https://github.com/atlas-engineer/ndebug), [nfiles](https://github.com/atlas-engineer/nfiles), [ntemplate](https://github.com/atlas-engineer/ntemplate), [nkeymaps](https://github.com/atlas-engineer/nkeymaps).

**Comment by vindarel** [comment]
Hi, thanks. nkeymaps might be too specialized, and we don't see what ntemplates brings (can't see what the generated template is) (it *reads* specific to Atlas projects too). 

nfiles seems to do a lot, but isn't the first example typically solved with a function?

```lisp
(defvar *foo-path* (uiop:xdg-config-home))
;; =»
(defvar *foo-path*)
(defun foo-path ()
  (if (boundp '*foo-path*)
     *foo-path*
     (setf *foo-path* (uiop:xdg-config-home))) ;; you got the idea
```

**Comment by aartaka** [comment]
>Hi, thanks. nkeymaps might be too specialized, 

Fair points. That's exactly the reason I've separated commits—you can remove/modify them whenever you find it right.

>and we don't see what ntemplates brings (can't see what the generated template is) (it *reads* specific to Atlas projects too). 

While it's opinionated (BSD license, NASDF build extension, several hard-coded repository links), that's mostly due to Quickproject limitations. Even with these limitations, the skeleton saves some hour of work even for non-Atlas libraries (like my https://github.com/aartaka/graven-image)

>nfiles seems to do a lot, but isn't the first example typically solved with a function?
>
>```lisp
>(defvar *foo-path* (uiop:xdg-config-home))
>;; =»
>(defvar *foo-path*)
>(defun foo-path ()
>  (if (boundp '*foo-path*)
>     *foo-path*
>     (setf *foo-path* (uiop:xdg-config-home))) ;; you got the idea
>```

Well, that's only the first example among many others. As a wider and more realistic set of examples, Nyxt use-cases for it are:
- User scripts and block lists fetched remotely and refreshed daily/hourly.
- Lisp files with dumped objects (de)serializable with cl-prevalence.
-  Mixins for read-only, virtual, remote, data/config/runtime/cache files.

And yes, path resolution part you've highlighted is there in the library. But there's also file watching, object persistence, synchronization, user profiles—basically all the stuff I've listed. And, likely, some more that I've forgotten.

**Comment by aartaka** [comment]
Cool, thanks @vindarel!

**Pull request closed without merging**
