### PR TITLE
Series - functional style without runtime penalty at all

### PR DESCRIPTION
**Pull request by vindarel**
that looks awesome (yet with not modern api verbs) but it looks barely known out there !

On reddit, nobody has experience to share: https://www.reddit.com/r/Common_Lisp/comments/4elqdm/loops_in_lisp_part_4_series_macrology/

the sourceforge page is full of dead links, the svn repo isn't
reachable, but there's also a git repo and a github mirror, on which
wiki I have grouped all resources I found about this library.

### CODE REVIEW

**Comment by rmhsilva** [comment]
Series is great, but someone does need to write some evangelism about it! It's quite well documented in Common Lisp The Language (https://www.cs.cmu.edu/Groups/AI/util/html/cltl/clm/node1.html). See appendix A. Gotta love how long this stuff has been around for!

**Comment by vindarel** [comment]
totally agree ! and the "official" sourceforge page is as unfriendly as possible. At least I put together the links I saw about it: https://github.com/tokenrove/series/wiki/Documentation  including the link to CL the Language you give. It's been around since 1989.

**Comment by rmhsilva** [comment]
Ah I hadn't seen that malisper article, thanks! I'll try and write some series info at some point...

**Comment by vindarel** [comment]
yes please ! Do you have yourself code samples to look at ?

**Comment by rmhsilva** [comment]
Nope, nothing available yet.

**Comment by vindarel** [comment]
furthermore I built an api documentation with Codex (CommonDoc): https://vindarel.github.io/series/ there are some gaps though.

**Comment by CodyReichert** [comment]
Very cool, thank you!

**Pull request merged**
