### PR TITLE
Add Sketch

### PR DESCRIPTION
**Pull request by rmhsilva**

### CODE REVIEW

**Comment by CodyReichert** [comment]
Oh that's really neat, thanks!

**Comment by rmhsilva** [comment]
Thanks @vydd!

**Comment by vindarel** [comment]
@rmhsilva just discovered your blog[1]: there are very clear resources there (welcome post on packages and all). I invite you to have a look at the [CL Cookbook](https://github.com/LispCookbook/cl-cookbook) :] I believe it is the best place to build a rich community-driven resource that CL needs and presently lacks. Hope to see you there !

1: http://lispmethods.com/

**Comment by vydd** [comment]
@rmhsilva @CodyReichert thanks for adding Sketch, guys!

**Pull request merged**
