### PR TITLE
add Flute html generator, cl-who not the first choice.

### PR DESCRIPTION
**Pull request by vindarel**

### CODE REVIEW

**Comment by Harleqin** [comment]
The link is missing.

Also, as far as I see, there is no process to assess the relative merits of alternatives in awesome-cl (you might say that everything here is _awesome_).  How do you then justify the re-ordering?

As an aside, I am always very cautious about libraries and systems claiming that they are "simple" or "easy".

My proposal, absent aforementioned process, would be to sort things that are in the same bucket in alphabetic order, _maybe_ disregarding the all-too-common `cl-` prefix.

**Comment by CodyReichert** [comment]
Thanks @Harleqin! I fixed the link.

That's a good question, too. I'm not sure of the exact reason in this one, but overall it's a good question. Is there any merit for us to "promote" the most widely used package in the community, or similar? That might be too subjective.

I checked if there's any requirement from the parent awesome project, but he has [an interesting take on alphabetizing the entries](https://github.com/sindresorhus/awesome/issues/548#issuecomment-189576619). He does say that new entries are added to the end, though, so there's some process.

Thoughts?

**Comment by vindarel** [comment]
oops, thanks. 

I take this approach, sort of: by default, add an entry to the end. In some sections it is clear to me, for the sake of newcomers, that de-facto libraries should come first, like Quicklisp or bordeaux-threads. Sometimes I think that two libraries are very similar in scope and should be side by side, like Spinneret and Flute. Spinneret was there so I added Flute below. And sometimes there's some curation based on the experience I had.

 In this case, I didn't like cl-who and found spinneret much easier and much more feature-full, hence the little regression of cl-who. But it wasn't necessary, I should have touched cl-who in another PR. Actually I'm thinking of doing one to remove it. I'll wait longer for some approval or reject for this one.

As the sections are not very big (good), there aren't many remaining lines to sort, and I don't know what benefit it would bring.

I'm ok to state that we add libraries to the end.

ps: my process is also that I do everything with PRs and I wait at least a day for reactions.

**Comment by Harleqin** [comment]
I definitely would not remove `cl-who`.  For one, it is well written, very mature, and very well documented.  It is also used in a lot of projects and production systems, a _de facto_ default library, and there were few alternatives for a long time.

**Comment by vindarel** [comment]
ok ! Thanks for the rationale.

**Comment by CodyReichert** [comment]
Thank you both for your input here - it really helps improve over quality. CL newcomers and even existing users will benefit from the discussions on what are de-facto libraries  and which one's are available here. Hopefully the current system helps foster that and, if/where it doesn't I think we're all open to fixing it.

**Pull request merged**
