### PR TITLE
rm 2dsyntax

### PR DESCRIPTION
**Pull request by vindarel**
it's unreachable. Project pages show 404 error. Not on Quicklisp, thus not on Quickdoc.

### CODE REVIEW

**Comment by jakykong** [comment]
I believe this project has simply moved:
http://hyperprostor.g6.cz/lisp/cl-2dsyntax/

(Link from original author on this thread: http://www.lispforum.com/viewtopic.php?f=2&t=3492 )

**Comment by vindarel** [comment]
Cool thanks, I'll fix the links then.

**Comment by jakykong** [comment]
Glad to help!

**Comment by vindarel** [comment]
I edited the Cliki page.

**Pull request closed without merging**
