### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anweshknayak**

### CODE REVIEW

**Comment by Harleqin** [comment]
I see many problems with the lisp koans, and I would not want beginners to learn from that in the present form.

**Comment by Harleqin** [comment]
Also, please be more descriptive in your  commit messages.  Here, I'd say „Add lisp koans to README.md“.

**Comment by anweshknayak** [comment]
Then may be in the intermediate one ?
I myself as a beginner found it to be quite easy.

**Comment by Harleqin** [comment]
Non-beginners do not have much to learn from it.

I like the idea, and I guess it was a nice experience for the beginner who wrote it, but it needs a lot of work before it should be used to teach others.

**Comment by CodyReichert** [comment]
Hi, @anweshknayak - thanks for the PR. I'm going to merge this as-is, as I think it's a decent resource that people might not find otherwise.

@Harleqin If you think this is better off in the Intermediate section (or a new section like "Exercises" or "Misc" then I will also accept a PR or issue for that.

Thank you both for contributing!

**Pull request merged**
