### PR TITLE
add Rove unit testing package

### PR DESCRIPTION
**Pull request by momozor**
* also available in Quicklisp

### CODE REVIEW

**Comment by vindarel** [comment]
Thanks !

I'd be in favor of removing Prove at the same time. Prove has limitations and Rove is "officially" a replacement. Thoughts someone ?

**Comment by momozor** [comment]
I'm not entirely sure about this, because rove is still in BETA phase as stated from its README. Maybe just leave prove as it is for a while until the maintainer/owner say otherwise?

**Comment by vindarel** [comment]
mmh "beta" in Lisp is usually solid and can last long ! I'd like also to do a little bit of curation.

**Comment by momozor** [comment]
well..you are correct on the long lasting and solid part. They tend to be already mostly refined.

Maybe just discard Prove? It seems, the empty project template generator such as this one (owned by the same person, not surprisingly) is starting to include rove as the primary testing framework https://github.com/fukamachi/cl-project/blob/c06fa5b6784855db14d08db09e49307e992b4098/skeleton/skeleton.asd

**Comment by vindarel** [comment]
\+1 good info. I know, we'll cite Prove on the same line of Rove.

**Comment by momozor** [comment]
thanks

**Pull request merged**
