### PR TITLE
Add information about #lisp, #clschool, #lispcafe

### PR DESCRIPTION
**Pull request by susam**
This pull request is based on #404. Please merge #404 before merging this.

### CODE REVIEW

**Review by phoe — APPROVED** [review]

**Comment by vindarel** [comment]
Hi @CodyReichert, shall we add another developer in, such as phoe?

**Comment by phoe** [comment]
Thanks for the offer. I think that if I ever contribute then it'll be in form of PRs, so unless you need someone to help with merging, I don't think it will be necessary.

**Comment by vindarel** [comment]
ACK. Yes I think we could have more hands to merge PRs (especially for summer where we can be AFK).

**Comment by vindarel** [comment]
@susam thanks! (and for speciifying the order)

**Comment by phoe** [comment]
OK. I don't think I have much free time to review PRs on my own, but I'll be able to hit the merge button if you ping me hard enough.

**Comment by vindarel** [comment]
OK. You approved these changes by yourself though ;) it looks like you were reviewing PRs.

**Comment by phoe** [comment]
That's a single incident rather than the regular flight plan, though. I was involved in the migration to Libera, hence I was able to review and add some information myself.

**Pull request merged**
