### PR TITLE
Added gtwiwtg

### PR DESCRIPTION
**Pull request by mdbergmann**

### CODE REVIEW

**Comment by vindarel** [comment]
Good find! You advertise it on social networks first to see if something useful comes out?

**Comment by mdbergmann** [comment]
I was exploring lazy sequences. The usual choice, Series, is good, but the API is very different compared to Clojure, Haskell or other functional languages.
There are a few wrappers, like folio2. But Folio2 generates more confusion with the mixup of FSet and Series.
Anyway, the author did write a comment in Reddit that I fortunately could recall. https://www.reddit.com/r/Common_Lisp/comments/hr3ibu/taps_a_small_number_of_functions_that_make_series/

This library has a good documentation and test code (not enough, but maybe sufficient).

Having sais all this I just realized that this project is not in quicklisp.
Should it be?
And you suggest to first bring it up in Reddit or so?

**Comment by vindarel** [comment]
Being in Quicklisp is not a prerequisite for inclusion here. 

Indeed I suggest a post on reddit.

**Comment by vindarel** [comment]
> I was exploring lazy sequences. The usual choice, Series, is good, but the API is very different compared to Clojure, Haskell or other functional languages. There are a few wrappers, like folio2. But Folio2 generates more confusion with the mixup of FSet and Series.

absolutely. This (weirdly named) library seems very welcome, filling a gap.

**Pull request merged**
