### PR TITLE
Added hackr.io

### PR DESCRIPTION
**Pull request by HoodaSaurabh**
Have a look at these programming community curated resources for learning LISP -- https://hackr.io/tutorials/learn-lisp

### CODE REVIEW

**Comment by vindarel** [comment]
Hello, this is a link to a list of resources inside our list of resources. I'd like to ask you what this brings to us, but you are biased :p

**Comment by HoodaSaurabh** [comment]
Hello @vindarel, may I know what made you think we are biased? I would like to remove those biases:)

**Comment by vindarel** [comment]
you are the founder of hackr.io :)

**Comment by CodyReichert** [comment]
I'm going to agree with @vindarel on this one that since it's not a link directly to a resource it shouldn't be added. We can't keep checking up on that page individually to make sure it stays awesome :sunglasses: 

Additionally, we do a lot of resources from that page already in the list. If there's any we're missing and you want to PR a link to them directly, those can most definitely can be looked at. At the end of the day, the links should be directly to the Lisp resources, I think, but let me know if anyone thinks otherwise.

---

One alternative idea is to have a new "Forums" or "Communities" section. I'm not sure if there's enough to populate it (maybe links to Reddit also), but we can think about something like that.

**Comment by HoodaSaurabh** [comment]
@vindarel: ohh, I got it now. I was wondering [other kinds](https://en.wikipedia.org/wiki/List_of_cognitive_biases) of biases :)

**Comment by HoodaSaurabh** [comment]
@CodyReichert : Point taken.

**Pull request closed without merging**
