### PR TITLE
inline project links, except licences

### PR DESCRIPTION
**Pull request by vindarel**
for easier collaboration,
fixing a few duplicates and missing links.

viva emacs' macros
and a little check with

    grep -Eo "\[[0-9]+\]" README.md | grep -Eo "[0-9]+" | uniq | sort -g

as discussed in PR https://github.com/CodyReichert/awesome-cl/pull/34 !

### CODE REVIEW

**Comment by vindarel** [comment]
the link checker finds a dupe

> https://github.com/sindresorhus/awesome

but as it's in a badge url I don't feel in charge of fixing it here.

**Comment by CodyReichert** [comment]
Hey @vindarel -- I apologize for the slow reply here (been swamped), but this is really great, thanks for working on it!

Are you ready for this to be merged? The diff looks good to me, but it's big so I just wanted to confirm before pulling it in.

**Comment by vindarel** [comment]
Hi ! Yes this looks good to me. I didn't click on all links, but I double-checked nothing was forgotten with the little command line I gave in the comment. (There may be some erroneous links, but from before this edit).

**Comment by CodyReichert** [comment]
Thank you :)

**Comment by rmhsilva** [comment]
FYI, looks like this did break at least one link (plump in the html parsing section - it is also in the xml section). Might be worth going over them all. I'll open a new issue if I find any others.

**Comment by vindarel** [comment]
thanks. This is for plump: https://github.com/CodyReichert/awesome-cl/pull/38

**Comment by CodyReichert** [comment]
Good find @rmhsilva - I just merged #38 from @vindarel! Might be easier to find any other broken ones I re-deploy the GitHub pages site, so I'll try and do that shortly.

**Comment by rmhsilva** [comment]
@CodyReichert sweet, sounds good (Y)

**Pull request merged**
